server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  # h2
  datasource:
    url: jdbc:h2:mem:kpsecdb;MODE=MySQL;DATABASE_TO_UPPER=false;
    platform: h2
    username: kpsec
    password: kpsec
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  # jpa
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: h2

  #devtool      
  devtools:
    livereload:
      enabled: true